name: CIoo
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      
      # Build
      
      - name: Percy Test
        run: yarn percy exec -- cypress run --spec .\cypress\e2e\specs\smoke-specs\cookie-consent\careers.cy.js
